name: Helpers-test
on:
  #workflow_run:
  #  workflows: ["Pull Request Tests"]
  #  types:
  #    - requested
  pull_request:
    branches:
      - main
env:
  app: Accept:application/vnd.github.v3+json
  base_url: $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/runs
  AUTH: ${{ secrets.GITHUB_TOKEN }}

jobs:
  pre:
    name: Preprocess
    runs-on: ubuntu-latest

    steps:
    - name: Share helper id
      run: echo -n ${{ github.run_id }} >~/id_file

    - uses: actions/cache@v2
      with:
        path: ~/id_file
        key: helperid-${{ github.event.workflow_run.id }}

  repocheck:
    name: Repo check
    runs-on: ubuntu-20.04

    steps:
    - name: Check up-to-dateness and post comment
      run: |
        echo $helperid
        head_sha=${{ github.event.pull_request.head.sha }}
